Rscript prepCountInputs.R 1
Rscript prepCountInputs.R 2
Rscript prepCountInputs.R 3
Rscript prepCountInputs.R 4
Rscript prepCountInputs.R 5
Rscript prepCountInputs.R 6
Rscript prepCountInputs.R 7
Rscript prepCountInputs.R 8
Rscript prepCountInputs.R 9
Rscript prepCountInputs.R 10
Rscript prepCountInputs.R 11
Rscript prepCountInputs.R 12
Rscript prepCountInputs.R 13
Rscript prepCountInputs.R 14
Rscript prepCountInputs.R 15
Rscript prepCountInputs.R 16
Rscript prepCountInputs.R 17
Rscript prepCountInputs.R 18
Rscript prepCountInputs.R 19
Rscript prepCountInputs.R 20
Rscript prepCountInputs.R 21
Rscript prepCountInputs.R 22
Rscript prepCountInputs.R 23
Rscript prepCountInputs.R 24
Rscript prepCountInputs.R 25
Rscript prepCountInputs.R 26
Rscript prepCountInputs.R 27
Rscript prepCountInputs.R 28
Rscript prepCountInputs.R 29
Rscript prepCountInputs.R 30
Rscript prepCountInputs.R 31
Rscript prepCountInputs.R 32
Rscript prepCountInputs.R 33
Rscript prepCountInputs.R 34
Rscript prepCountInputs.R 35
Rscript prepCountInputs.R 36
Rscript prepCountInputs.R 37
Rscript prepCountInputs.R 38
Rscript prepCountInputs.R 39
Rscript prepCountInputs.R 40
Rscript prepCountInputs.R 41
Rscript prepCountInputs.R 42
Rscript prepCountInputs.R 43
Rscript prepCountInputs.R 44
Rscript prepCountInputs.R 45
Rscript prepCountInputs.R 46
Rscript prepCountInputs.R 47
Rscript prepCountInputs.R 48
Rscript prepCountInputs.R 49
Rscript prepCountInputs.R 50
